name: firebase_messaging
description: Flutter plugin for Firebase Cloud Messaging, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging
version: 6.0.15

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasemessaging
        pluginClass: FirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin

dependencies:
  meta: ^1.0.4
  platform: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.3.0
  mockito: ^3.0.0
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
